/**
 * Downloads the resume PDF from siteConfig.resumeUrl (Google Drive),
 * extracts text, and writes src/data/resume.generated.ts.
 *
 * Usage:
 *   npm run sync:resume
 *
 * Workflow:
 *   1. Update the PDF on Google Drive (same link), OR change resumeUrl in content.ts
 *   2. Run npm run sync:resume
 *   3. Commit the regenerated file and deploy
 *
 * Deploy also runs this before build so production stays current with Drive.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PDFParse } from "pdf-parse";
import { siteConfig } from "../src/data/content";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/data/resume.generated.ts");

function extractDriveFileId(url: string): string {
  const match =
    url.match(/\/file\/d\/([^/]+)/) ||
    url.match(/[?&]id=([^&]+)/) ||
    url.match(/^([a-zA-Z0-9_-]{20,})$/);
  if (!match?.[1]) {
    throw new Error(
      `Could not parse a Google Drive file id from resumeUrl: ${url}`
    );
  }
  return match[1];
}

async function downloadDrivePdf(fileId: string): Promise<Buffer> {
  const url = `https://drive.google.com/uc?export=download&id=${fileId}`;
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) {
    throw new Error(`Failed to download resume (${res.status}): ${url}`);
  }

  const contentType = res.headers.get("content-type") ?? "";
  const buf = Buffer.from(await res.arrayBuffer());
  const isPdf = buf.subarray(0, 5).toString("utf8") === "%PDF-";

  // Drive sometimes returns an HTML interstitial for large/virus-scanned files.
  if (!isPdf || contentType.includes("text/html")) {
    const html = buf.toString("utf8");
    const confirm =
      html.match(/confirm=([0-9A-Za-z_]+)/)?.[1] ||
      html.match(/name="confirm"\s+value="([^"]+)"/)?.[1];
    if (!confirm) {
      throw new Error(
        "Google Drive returned HTML instead of a PDF. Make sure the file is shared as 'Anyone with the link'."
      );
    }
    const retry = await fetch(
      `https://drive.google.com/uc?export=download&id=${fileId}&confirm=${confirm}`,
      { redirect: "follow" }
    );
    if (!retry.ok) {
      throw new Error(`Resume download retry failed (${retry.status})`);
    }
    const retryBuf = Buffer.from(await retry.arrayBuffer());
    if (retryBuf.subarray(0, 5).toString("utf8") !== "%PDF-") {
      throw new Error("Downloaded file is not a PDF after confirm retry.");
    }
    return retryBuf;
  }

  return buf;
}

function cleanResumeText(raw: string): string {
  return raw
    .replace(/\r\n/g, "\n")
    // Drop private-use / icon-font glyphs, keep normal Latin text
    .replace(/[\u0080-\u009F\uE000-\uF8FF]/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/W ARANGAL/g, "WARANGAL")
    .replace(/A WS/g, "AWS")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/\n-- \d+ of \d+ --\s*$/g, "")
    .trim();
}

function toTsModule(text: string, meta: {
  sourceUrl: string;
  fileId: string;
  pages: number;
  syncedAt: string;
}): string {
  return `/**
 * AUTO-GENERATED by \`npm run sync:resume\`. Do not edit by hand.
 * Source: ${meta.sourceUrl}
 * Synced: ${meta.syncedAt}
 * Pages: ${meta.pages}
 */
export const resumeSyncedAt = ${JSON.stringify(meta.syncedAt)};
export const resumeSourceUrl = ${JSON.stringify(meta.sourceUrl)};
export const resumeFileId = ${JSON.stringify(meta.fileId)};
export const resumePageCount = ${meta.pages};

export const resumeText = ${JSON.stringify(text)};
`;
}

async function main() {
  const sourceUrl = siteConfig.resumeUrl;
  const fileId = extractDriveFileId(sourceUrl);
  console.log(`Downloading resume from Drive id=${fileId} …`);

  const pdf = await downloadDrivePdf(fileId);
  console.log(`Downloaded ${pdf.length} bytes`);

  const parser = new PDFParse({ data: pdf });
  const parsed = await parser.getText();
  await parser.destroy();
  const text = cleanResumeText(parsed.text);
  if (text.length < 80) {
    throw new Error(
      `Extracted resume text looks too short (${text.length} chars). Aborting.`
    );
  }

  const syncedAt = new Date().toISOString();
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(
    OUT,
    toTsModule(text, {
      sourceUrl,
      fileId,
      pages: parsed.total,
      syncedAt,
    }),
    "utf8"
  );

  console.log(`Wrote ${OUT}`);
  console.log(`Extracted ${text.length} chars across ${parsed.total} page(s)`);
  console.log(`Synced at ${syncedAt}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
